#! /bin/bash

clear
echo "----------------------------------------------------------------------------------------------"

echo " -- START MAKE -- "
make

echo $'\n ----  CALC  ---- '
cat calc.txt
echo ''

echo $'\n ---  LAUNCH  --- '
echo "    START: " && date +"%T"
valgrind ./Bin/diff $@ 
echo "    END: "   && date +"%T"

echo $'\n ----  DUMP  ---- '
cat Txt/dump_BufNodes.txt
fim Txt/dump_tree_rls.jpeg